### ISSUE TITLE
vue.runtime.esm.js?2b0e:619 [Vue warn]: Error in render: "TypeError: Vue.component is not a function"

### ISSUE THREAD

**Issue by vik17ag** [woohyeonjo/page-translator#1]
I imported library using -
`import pageTranslator from '@nnm/page-translator';
    Vue.use(pageTranslator);`
And added 
`<page-translator target="language code ex) en, ko ..."
							 position="left"
							 apikey="[api-key]"
			></page-translator>`

in template. But console giving error in the subject. Pls help

**Comment by woohyeonjo** [comment]
You need to put the code of the target language you want to translate
ex) if you want to translate to English
      target="en"

**Comment by vik17ag** [comment]
thanks, it works

**Comment by vik17ag** [comment]
final code - 
`<page-translator target="ko" position="left" apikey="kblskdbvsjn;kbvsljblvjbrfj" ></page-translator>`

**Comment by woohyeonjo** [comment]
Do not open your API key. It is your private key. I'll erase the key you wrote :)
